config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :books
  resources :users
  
  get '/home/about'=>'homes#about', as: 'about'
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  has_one_attached :profile_image
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
    

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :books, dependent: :destroy
         
  validates :name, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
                   
  validates :introduction, length: { maximum: 50 }
         
    has_one_attached :profile_image
    
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
 def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
 end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = 'You have created book successfully.'
    redirect_to book_path(@book)
    else
     @books = Book.all
     @user = current_user
    render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    
  end

  def show
    @book = Book.new
    @hon = Book.find(params[:id])
    @user = @hon.user
  end
  
  def edit
   @book = Book.find(params[:id])
   unless @book.user == current_user
     redirect_to books_path
   end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
    redirect_to book_path(@book)
    else
    render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit]
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
  end
  
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
    redirect_to user_path(current_user)
    else
    render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:profile_image, :introduction)
  end
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this obj from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
      <%= form_with model: @book do |f| %>
      <div class="form-group">
      <label>Title</label><br>
      <%= f.text_field :title %><br>
      </div>
      <div class="form-group">
      <label>Opinion</label><br>
      <%= f.text_area :body %><br>
      </div>
      <%= f.submit 'Update Book', class:"btn btn-success" %><br>
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container">
<div class="row">
  <%= render 'users/list', book: @book, user: @user %>
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table">
  <tbody>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
    <% @books.each do |book| %>
     <tr>
      <td>
        <%= link_to user_path(book.user) do %>
        <%= image_tag book.user.get_profile_image(100, 100) %>
        <% end %>
       </td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
    </tr>
    <% end %>

  </tbody>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<% flash.each do |message_type, message| %>
<%= message %>
<% end %>
<div class="container">
  <div class="row">
    <%= render 'users/list', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <th>
              <%= link_to user_path(@user) do %>
              <%= image_tag @user.get_profile_image(100, 100) %><br>
              <%= @user.name %>
              <% end %>
            </th>
            <td><%= link_to @hon.title %></td>
            <td><%= @hon.body %></td>
            <% if @hon.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@hon), class:"btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@hon), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-sm btn-danger" %></td>
            <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="row">
<h1 class="px-3 mx-auto">
  Welcome to
  <strong><i class="fas fa-book"></i>Bookers</strong>
  !
</h1>
</div>

app/views/homes/top.html.erb
<% flash.each do |message_type, message| %>
<%= message %>
<% end %>
<div class="container">
<div class="row">
  <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
<h1>welcome to
<i class="fas fa-book"></i>
<strong>Bookers</strong>
!!
</h1>
<p>In
<strong><i class="fas fa-book"></i>Bookers</strong>
,
</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>

<div class="btn-wrapper col-10 mx-auto">
  <div class="row">
    <%= link_to 'ゲストログイン(閲覧用)', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
  </div>
  <div class="row">
    <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
  </div>
  <div class="row">
    <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block" %>
  </div>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "/", class:"nav-barbrand nav-link text-white" do %>
        <span class="bookers">Bookers</span>
        <% end %>
      
      
      
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to user_path(current_user), class:"nav-link text-white" do %>
        <i class="fas fa-home"></i>
        <span>Home</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to users_path, class:"nav-link text-white" do %>
        <i class="fas fa-users"></i>
        <span>Users</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to books_path, class:"nav-link text-white" do %>
        <i class="fas fa-book-open"></i>
        <sapn>Books</sapn>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-white" do %>
        <i class="fas fa-sign-out-alt"></i>
        <sapn>Log out</sapn>
        <% end %>
      </li>
      
    <% else %>
      <li class="nav-item">
        <%= link_to "/", class:"nav-link text-white" do %>
        <i class="fas fa-home"></i>
        <span>Home</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to about_path, class:"nav-link text-white" do %>
        <i class="fas fa-link"></i>
        <span>About</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_registration_path, class:"nav-link text-white" do %>
        <i class="fas fa-user-plus"></i>
        <span>Sign up</span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_session_path, class:"nav-link text-white" do %>
        <i class="fas fa-sign-in-alt"></i>
        <span>Log in</span>
        <% end %>
      </li>
    <% end %>
    </ul>
    </div>
    </nav>
  </header>
  <main>
    <div class="container">
      <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6"></div>
      </div>
    </div>
  
    <%= yield %>
  </main>
  
  </body>
  <footer>
    <div class="cantainer mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
</html>

app/views/users/_list.html.erb
<div class="col-md-3">
<h2>User Info</h2>
<%= image_tag user.get_profile_image(100, 100) %>

<table class="table">
  <tbody>
    <tr>
    <th>name</th>
    <td><%= user.name %></td>
    </tr>
    <tr>
    <th>introduction</th>
    <td><%= user.introduction %></td>
    </tr>
  </tbody>
</table>
<% if user.name != "guestuser" %>
<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>
<% end %>

  <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block edit_user_path" do %> 
    <i class="fas fa-user-cog"></i>
  <% end %>
<h2>New book</h2>
  <%= form_with model: book do |f| %>
  <label>Title</label><br>
  <%= f.text_field :title %><br>
	
  <label>Opinion</label><br>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>

</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <ul>
  <% @user.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
  </ul>
<% end %>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label><br>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name" %><br>
  <label for="inputImage">Image</label><br>
  <%= f.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*" %><br>
  <label for="inputIntroduction">Introduction</label><br>
  <%= f.text_area :introduction %><br>
  <%= f.submit "Update User", class:"btn btn-secondary" %>
<% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row">
  <%= render 'list', user: @user, book: @book  %>
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  
  <table class="table">
    <tbody>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
      <% @users.each do |user| %>
      <tr>
        <td><%= link_to user_path(user) do %>
        <%= image_tag user.get_profile_image(100, 100) %>
        <% end %>
        </td>
        <td><%= user.name %></td>
        <td>
          <%= link_to "Show", user_path(user) %>
        </td>
      </tr>
      <% end %>
      </tbody>
  </table>
  </div>
</div>
</div>

app/views/users/show.html.erb
<% flash.each do |message_type, message| %>
<%= message %>
<% end %>
<div class="container">
  <div class="row">
    <%= render 'list', book: @book, user: @user %>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% @user.books.each do |hon| %>
              <tr>
              <td>
                <%= link_to user_path(@user) do %>
                <%= image_tag @user.get_profile_image(100, 100) %>
                <% end %>
              </td>
              <td>
                <%= link_to hon.title, book_path(hon) %>
              </td>
              <td>
                <%= hon.body %>
              </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    
  